apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service-1
  labels:
    app: dispatcher-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service-1
  template:
    metadata:
      labels:
        app: dispatcher-service-1
    spec:
      containers:
        - name: dispatcher-service-1
          image: dispatcher-service-1
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          env:
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq-1