apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service-1
  labels:
    app: dispatcher-service-1
spec:
  type: ClusterIP
  selector:
    app: dispatcher-service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003